blas mlir kernels pass unit tests.
tensorflow/runtime pull request #87
Opened 2022-01-19 02:44 UTC by weihanmines

Thanks for your contribution! Unfortunately, tensorflow/runtime is currently not
accepting contributions. Please see the
[Contribution Guidelines](../blob/master/README.md#contribution-guidelines) for
more information.

2022-01-19 15:42 UTC, deven-amd commented
/cc @chsigg @hanbinyoon 

@weihanmines please update the PR to only include changes related to getting the `blas.mlir` unit test working on ROCm.

@chsigg @hanbinyoon , please review and let us know if we are going down the right path...thanks.

2022-01-25 19:30 UTC, chsigg requested changes

2022-01-25 19:30 UTC, chsigg commented on backends/gpu/lib/kernels/blas_kernels.cc
> +  rocblas_datatype data_type = wrapper::BlasDataType::FromOpaqueValue(*dataType);
This should be 'BlasDataType' to support both CUDA and ROCm.

2022-01-25 19:30 UTC, chsigg commented on backends/gpu/lib/kernels/blas_kernels.cc
> +  if (platform != wrapper::Platform::CUDA && platform != wrapper::Platform::ROCm)
You can remove this once we support both CUDA and ROCm.

2022-01-25 19:30 UTC, chsigg commented on backends/gpu/lib/kernels/blas_kernels.cc
> +    return wrapper::RocblasTrsmBatched(
I want to suggest that you add a BlasTrsmBatched to blas_wrapper.h/cc and call that from here. But complex types are different for CUDA and ROCm. So likely we want to take care of the `TODO` above CublasTrsmBatched and provide a type-punned entry point instead (plus an platform abstracted version).

2022-01-25 19:30 UTC, chsigg commented on backends/gpu/lib/kernels/blas_kernels.cc
> +    ptrdiff_t a_batch_stride = (side_mode == rocblas_side_left) ? m * m : n * n;
I think this can be `size_mode == CUBLAS_SIDE_LEFT || size_mode == rocblas_size_left`

2022-01-25 19:30 UTC, chsigg commented on backends/gpu/mlir_tests/rocm/blas.mlir
> +func @blas_axpy() {
I don't see what's changed from the cuda/blas.mlir file. I assume it's just replacing the CUDA constants with ROCm constants?

2022-01-25 19:30 UTC, chsigg commented on backends/gpu/tools/stub_codegen/hip.json
> +   "header":"/opt/rocm-4.5.2/include/hip/hip_runtime.h",
These changes are good, but can we split them out?

2022-01-28 01:24 UTC, hanbinyoon reviewed
Just testing.

2022-03-02 18:43 UTC, weihanmines commented
> Hi Wei, what is the status of this PR?

I will have a follow up based on your changes soon.

2022-03-02 18:46 UTC, weihanmines commented
> Hi Wei, what is the status of this PR?

Hi Christian, we probably can close this PR since this one is the same as PR #97. Do you mind if I close this PR? The changes regarding to blas mlir can be tracked in the PR #97 .

2022-03-03 12:21 UTC, chsigg commented
Will do, thanks Wei.

2022-03-03 12:21 UTC, closed without merging